// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/raven.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicaMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,4,opt,name=partition,proto3" json:"partition,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaMessage) Reset() {
	*x = ReplicaMessage{}
	mi := &file_proto_raven_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaMessage) ProtoMessage() {}

func (x *ReplicaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raven_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaMessage.ProtoReflect.Descriptor instead.
func (*ReplicaMessage) Descriptor() ([]byte, []int) {
	return file_proto_raven_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicaMessage) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReplicaMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplicaMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ReplicaMessage) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ReplicaMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ReplicateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateResponse) Reset() {
	*x = ReplicateResponse{}
	mi := &file_proto_raven_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateResponse) ProtoMessage() {}

func (x *ReplicateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raven_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateResponse.ProtoReflect.Descriptor instead.
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return file_proto_raven_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplicateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_raven_proto protoreflect.FileDescriptor

const file_proto_raven_proto_rawDesc = "" +
	"\n" +
	"\x11proto/raven.proto\x12\x05raven\"\x95\x01\n" +
	"\x0eReplicaMessage\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x04 \x01(\x05R\tpartition\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"C\n" +
	"\x11ReplicateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2R\n" +
	"\x12ReplicationService\x12<\n" +
	"\tReplicate\x12\x15.raven.ReplicaMessage\x1a\x18.raven.ReplicateResponseB Z\x1egithub.com/Xenios7/Raven/protob\x06proto3"

var (
	file_proto_raven_proto_rawDescOnce sync.Once
	file_proto_raven_proto_rawDescData []byte
)

func file_proto_raven_proto_rawDescGZIP() []byte {
	file_proto_raven_proto_rawDescOnce.Do(func() {
		file_proto_raven_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_raven_proto_rawDesc), len(file_proto_raven_proto_rawDesc)))
	})
	return file_proto_raven_proto_rawDescData
}

var file_proto_raven_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_raven_proto_goTypes = []any{
	(*ReplicaMessage)(nil),    // 0: raven.ReplicaMessage
	(*ReplicateResponse)(nil), // 1: raven.ReplicateResponse
}
var file_proto_raven_proto_depIdxs = []int32{
	0, // 0: raven.ReplicationService.Replicate:input_type -> raven.ReplicaMessage
	1, // 1: raven.ReplicationService.Replicate:output_type -> raven.ReplicateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_raven_proto_init() }
func file_proto_raven_proto_init() {
	if File_proto_raven_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_raven_proto_rawDesc), len(file_proto_raven_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_raven_proto_goTypes,
		DependencyIndexes: file_proto_raven_proto_depIdxs,
		MessageInfos:      file_proto_raven_proto_msgTypes,
	}.Build()
	File_proto_raven_proto = out.File
	file_proto_raven_proto_goTypes = nil
	file_proto_raven_proto_depIdxs = nil
}
